import type { Product, Order, Supplier, Invoice, Incident, Return, AnnualFee } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Uniforme de trabajo — talla M",
    description: "Uniforme oficial para el personal de tienda, tejido transpirable.",
    price: 45.99,
    unit: "unidad",
    category: "Equipamiento de personal",
    supplierId: "s1",
    supplierName: "Uniformes Pro S.L.",
    stock: 150,
    sku: "UNI-M-001",
  },
  {
    id: "p2",
    name: "Cartel de señalización interior",
    description: "Señalética normalizada para pasillos y zonas de tienda.",
    price: 12.5,
    unit: "unidad",
    category: "Señalética",
    supplierId: "s2",
    supplierName: "Señales y Displays S.A.",
    stock: 300,
    sku: "SEÑ-INT-002",
  },
  {
    id: "p3",
    name: "Caja registradora TPV",
    description: "Terminal punto de venta con pantalla táctil 15\".",
    price: 899.0,
    unit: "unidad",
    category: "Tecnología y TPV",
    supplierId: "s3",
    supplierName: "Tech Retail Solutions",
    stock: 20,
    sku: "TPV-015-003",
  },
  {
    id: "p4",
    name: "Papel térmico para tickets (caja 50 rollos)",
    description: "Rollos de papel térmico compatible con la mayoría de impresoras TPV.",
    price: 24.9,
    unit: "caja",
    category: "Consumibles",
    supplierId: "s3",
    supplierName: "Tech Retail Solutions",
    stock: 500,
    sku: "PAP-TER-004",
  },
  {
    id: "p5",
    name: "Balanza de mostrador certificada",
    description: "Balanza homologada con certificación OIML, capacidad 15 kg.",
    price: 320.0,
    unit: "unidad",
    category: "Pesaje y medición",
    supplierId: "s4",
    supplierName: "Metrología Ibérica",
    stock: 30,
    sku: "BAL-15K-005",
  },
  {
    id: "p6",
    name: "Sistema de refrigeración mural 2 m",
    description: "Mueble frigorífico mural de 2 metros para exposición de frescos.",
    price: 2400.0,
    unit: "unidad",
    category: "Equipamiento frigorífico",
    supplierId: "s5",
    supplierName: "Fríos Comerciales S.L.",
    stock: 8,
    sku: "FRI-MUR-006",
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-2024-001",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    items: [
      {
        productId: "p1",
        productName: "Uniforme de trabajo — talla M",
        supplierId: "s1",
        supplierName: "Uniformes Pro S.L.",
        quantity: 10,
        unitPrice: 45.99,
        subtotal: 459.9,
      },
      {
        productId: "p4",
        productName: "Papel térmico para tickets (caja 50 rollos)",
        supplierId: "s3",
        supplierName: "Tech Retail Solutions",
        quantity: 5,
        unitPrice: 24.9,
        subtotal: 124.5,
      },
    ],
    total: 584.4,
    status: "delivered",
    createdAt: "2024-11-15T09:00:00Z",
    updatedAt: "2024-11-20T14:30:00Z",
    deliveryAddress: "Calle Gran Vía 28, 28013 Madrid",
  },
  {
    id: "ORD-2024-002",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    items: [
      {
        productId: "p3",
        productName: "Caja registradora TPV",
        supplierId: "s3",
        supplierName: "Tech Retail Solutions",
        quantity: 2,
        unitPrice: 899.0,
        subtotal: 1798.0,
      },
    ],
    total: 1798.0,
    status: "shipped",
    createdAt: "2024-12-01T11:00:00Z",
    updatedAt: "2024-12-03T08:00:00Z",
    deliveryAddress: "Calle Gran Vía 28, 28013 Madrid",
  },
];

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "s1",
    name: "Uniformes Pro S.L.",
    email: "ventas@uniformespro.es",
    phone: "+34 91 234 5678",
    categories: ["Equipamiento de personal"],
    status: "active",
    totalProducts: 24,
  },
  {
    id: "s2",
    name: "Señales y Displays S.A.",
    email: "info@senalesdisplays.es",
    phone: "+34 93 456 7890",
    categories: ["Señalética"],
    status: "active",
    totalProducts: 45,
  },
  {
    id: "s3",
    name: "Tech Retail Solutions",
    email: "soporte@techretail.es",
    phone: "+34 91 876 5432",
    categories: ["Tecnología y TPV", "Consumibles"],
    status: "active",
    totalProducts: 37,
  },
  {
    id: "s4",
    name: "Metrología Ibérica",
    email: "comercial@metrologiaiberica.es",
    phone: "+34 95 321 0987",
    categories: ["Pesaje y medición"],
    status: "active",
    totalProducts: 12,
  },
  {
    id: "s5",
    name: "Fríos Comerciales S.L.",
    email: "ventas@frioscomerciales.es",
    phone: "+34 96 654 3210",
    categories: ["Equipamiento frigorífico"],
    status: "active",
    totalProducts: 18,
  },
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "FAC-2024-001",
    orderId: "ORD-2024-001",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    supplierId: "s1",
    supplierName: "Uniformes Pro S.L.",
    amount: 459.9,
    status: "paid",
    issuedAt: "2024-11-20T10:00:00Z",
    dueAt: "2024-12-20T10:00:00Z",
    items: [
      { description: "Uniforme de trabajo — talla M x10", quantity: 10, unitPrice: 45.99, subtotal: 459.9 },
    ],
  },
  {
    id: "FAC-2024-002",
    orderId: "ORD-2024-001",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    supplierId: "s3",
    supplierName: "Tech Retail Solutions",
    amount: 124.5,
    status: "paid",
    issuedAt: "2024-11-20T10:05:00Z",
    dueAt: "2024-12-20T10:05:00Z",
    items: [
      { description: "Papel térmico para tickets x5", quantity: 5, unitPrice: 24.9, subtotal: 124.5 },
    ],
  },
  {
    id: "FAC-2024-003",
    orderId: "ORD-2024-002",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    supplierId: "s3",
    supplierName: "Tech Retail Solutions",
    amount: 1798.0,
    status: "issued",
    issuedAt: "2024-12-03T09:00:00Z",
    dueAt: "2025-01-03T09:00:00Z",
    items: [
      { description: "Caja registradora TPV x2", quantity: 2, unitPrice: 899.0, subtotal: 1798.0 },
    ],
  },
];

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: "INC-2024-001",
    orderId: "ORD-2024-001",
    franchiseeId: "f1",
    type: "missing_item",
    description: "Faltan 2 uniformes de los 10 solicitados.",
    status: "resolved",
    createdAt: "2024-11-21T08:00:00Z",
    resolution: "Los 2 uniformes pendientes fueron entregados el 25/11/2024.",
  },
];

export const MOCK_RETURNS: Return[] = [
  {
    id: "DEV-2024-001",
    orderId: "ORD-2024-001",
    franchiseeId: "f1",
    items: [
      { productId: "p1", productName: "Uniforme de trabajo — talla M", quantity: 1, unitPrice: 45.99 },
    ],
    reason: "Talla incorrecta. Se solicitó cambio por talla L.",
    status: "completed",
    createdAt: "2024-11-22T09:00:00Z",
    refundAmount: 45.99,
  },
];

export const MOCK_ANNUAL_FEES: AnnualFee[] = [
  {
    id: "CUO-2024-001",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    year: 2024,
    amount: 1200.0,
    status: "paid",
    paidAt: "2024-01-10T10:00:00Z",
    dueAt: "2024-01-31T23:59:59Z",
  },
  {
    id: "CUO-2025-001",
    franchiseeId: "f1",
    franchiseeName: "Franquicia Carrefour Express Madrid Centro",
    year: 2025,
    amount: 1200.0,
    status: "pending",
    dueAt: "2025-01-31T23:59:59Z",
  },
];
